name: 'spring-boot-microservices-course'
services:
  prometheus:
    image: prom/prometheus:v2.53.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
